@ stub ClassInstall32
@ stdcall SCardAccessNewReaderEvent()
@ stdcall SCardReleaseAllEvents()
@ stdcall SCardReleaseNewReaderEvent()
@ stdcall SCardAccessStartedEvent()
@ stdcall SCardAddReaderToGroupA(long str str)
@ stdcall SCardAddReaderToGroupW(long wstr wstr)
@ stdcall SCardBeginTransaction(long)
@ stdcall SCardCancel(long)
@ stdcall SCardConnectA(long str long long ptr ptr)
@ stdcall SCardConnectW(long wstr long long ptr ptr)
@ stdcall SCardControl(long long ptr long ptr long ptr)
@ stdcall SCardDisconnect(long long)
@ stdcall SCardEndTransaction(long long)
@ stdcall SCardEstablishContext(long ptr ptr ptr)
@ stdcall SCardForgetCardTypeA(long str)
@ stdcall SCardForgetCardTypeW(long wstr)
@ stdcall SCardForgetReaderA(long str)
@ stdcall SCardForgetReaderGroupA(long str)
@ stdcall SCardForgetReaderGroupW(long wstr)
@ stdcall SCardForgetReaderW(long wstr)
@ stdcall SCardFreeMemory(long ptr)
@ stdcall SCardGetAttrib(long long ptr ptr)
@ stdcall SCardGetCardTypeProviderNameA(long str long str ptr)
@ stdcall SCardGetCardTypeProviderNameW(long wstr long wstr ptr)
@ stdcall SCardGetProviderIdA(long str ptr)
@ stdcall SCardGetProviderIdW(long wstr ptr)
@ stdcall SCardGetStatusChangeA(long long ptr long)
@ stdcall SCardGetStatusChangeW(long long ptr long)
@ stdcall SCardIntroduceCardTypeA(long str ptr ptr long ptr ptr long)
@ stdcall SCardIntroduceCardTypeW(long wstr ptr ptr long ptr ptr long)
@ stdcall SCardIntroduceReaderA(long str str)
@ stdcall SCardIntroduceReaderGroupA(long str)
@ stdcall SCardIntroduceReaderGroupW(long wstr)
@ stdcall SCardIntroduceReaderW(long wstr wstr)
@ stdcall SCardIsValidContext(long)
@ stdcall SCardListCardsA(long ptr ptr long str ptr)
@ stdcall SCardListCardsW(long ptr ptr long wstr ptr)
@ stdcall SCardListInterfacesA(long str ptr ptr)
@ stdcall SCardListInterfacesW(long wstr ptr ptr)
@ stdcall SCardListReaderGroupsA(long str ptr)
@ stdcall SCardListReaderGroupsW(long wstr ptr)
@ stdcall SCardListReadersA(long str str ptr)
@ stdcall SCardListReadersW(long wstr wstr ptr)
@ stdcall SCardLocateCardsA(long str ptr long)
@ stdcall SCardLocateCardsByATRA(long ptr long ptr long)
@ stdcall SCardLocateCardsByATRW(long ptr long ptr long)
@ stdcall SCardLocateCardsW(long wstr ptr long)
@ stdcall SCardReconnect(long long long long ptr)
@ stdcall SCardReleaseContext(long)
@ stdcall SCardReleaseStartedEvent()
@ stdcall SCardRemoveReaderFromGroupA(long str str)
@ stdcall SCardRemoveReaderFromGroupW(long wstr wstr)
@ stdcall SCardSetAttrib(long long ptr long)
@ stdcall SCardSetCardTypeProviderNameA(long str long str)
@ stdcall SCardSetCardTypeProviderNameW(long wstr long wstr)
@ stdcall SCardState(long ptr ptr ptr ptr)
@ stdcall SCardStatusA(long str ptr ptr ptr ptr ptr)
@ stdcall SCardStatusW(long wstr ptr ptr ptr ptr ptr)
@ stdcall SCardTransmit(long ptr ptr long ptr ptr ptr)
@ extern g_rgSCardRawPci
@ extern g_rgSCardT0Pci	
@ extern g_rgSCardT1Pci
